// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqkrcrtgcpdymluvelki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxa3JjcnRnY3BkeW1sdXZlbGtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1NTY1OTcsImV4cCI6MjA1NjEzMjU5N30.u_NWkQ_bNFWAPrs8dJY2vKAdh_hFmJzje5s84Bq4Pn4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);